{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.angerm.ag_server",
    "module": "redis",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-bom",
          "version": {
            "requires": "1.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-kotlin"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-logback"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-retrofit2"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-rxjava3"
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.uchuhimo",
          "module": "konf",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_hotspot",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_httpserver",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.1.2.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "redis-0.0.5.jar",
          "url": "redis-0.0.5.jar",
          "size": 14105,
          "sha512": "5a663ca2b833b81aa952ce3b4089314453e05333aba6788aeddb62838999698ac6cadffdeee597ce41654c5d4ba0de655e8cf1e66d7796a25393998db0670c7a",
          "sha256": "578fb2fb99cc198a0ca80075ca4d626e751abadbed16fbf07e0d705e9b6a9b24",
          "sha1": "ddc84354c7a854a6c8f75498748c0a45124691f2",
          "md5": "a97b140c971868745bde340bbfce2472"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "dev.angerm.ag_server",
          "module": "base",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-bom",
          "version": {
            "requires": "1.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-kotlin"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-logback"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-retrofit2"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-rxjava3"
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.uchuhimo",
          "module": "konf",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_hotspot",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_httpserver",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.1.2.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "redis-0.0.5.jar",
          "url": "redis-0.0.5.jar",
          "size": 14105,
          "sha512": "5a663ca2b833b81aa952ce3b4089314453e05333aba6788aeddb62838999698ac6cadffdeee597ce41654c5d4ba0de655e8cf1e66d7796a25393998db0670c7a",
          "sha256": "578fb2fb99cc198a0ca80075ca4d626e751abadbed16fbf07e0d705e9b6a9b24",
          "sha1": "ddc84354c7a854a6c8f75498748c0a45124691f2",
          "md5": "a97b140c971868745bde340bbfce2472"
        }
      ]
    }
  ]
}
