{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.angerm.ag_server",
    "module": "example",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-bom",
          "version": {
            "requires": "1.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-kotlin"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-logback"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-retrofit2"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-rxjava3"
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.uchuhimo",
          "module": "konf",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_hotspot",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_httpserver",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "example-0.0.1.jar",
          "url": "example-0.0.1.jar",
          "size": 11374,
          "sha512": "b358eb667bb9b12d1a3a160c81270ac02ebe314968de0967bdddde4e983dcb05f61bd712daefd94af0653b3ee166236eb92e6e03c796bc316204271a29aebe9b",
          "sha256": "ce712c6edc41158c394a792376d36dfcde5afff8c3156bc985fd7ebd92122662",
          "sha1": "329a915d8bda530bd0724a34f98b3f76e573055f",
          "md5": "35faed16002ab9bd2bf3dd4b3bb53e03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "dev.angerm.ag_server",
          "module": "base",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "dev.angerm.ag_server",
          "module": "redis",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "dev.angerm.ag_server",
          "module": "grpc",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-bom",
          "version": {
            "requires": "1.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-kotlin"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-logback"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-retrofit2"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-rxjava3"
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.uchuhimo",
          "module": "konf",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_hotspot",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_httpserver",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "example-0.0.1.jar",
          "url": "example-0.0.1.jar",
          "size": 11374,
          "sha512": "b358eb667bb9b12d1a3a160c81270ac02ebe314968de0967bdddde4e983dcb05f61bd712daefd94af0653b3ee166236eb92e6e03c796bc316204271a29aebe9b",
          "sha256": "ce712c6edc41158c394a792376d36dfcde5afff8c3156bc985fd7ebd92122662",
          "sha1": "329a915d8bda530bd0724a34f98b3f76e573055f",
          "md5": "35faed16002ab9bd2bf3dd4b3bb53e03"
        }
      ]
    }
  ]
}
