{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.angerm.ag_server",
    "module": "ag_server",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-bom",
          "version": {
            "requires": "1.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-kotlin"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-logback"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-retrofit2"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-rxjava3"
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.uchuhimo",
          "module": "konf",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_hotspot",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_httpserver",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ag_server-0.0.3.jar",
          "url": "ag_server-0.0.3.jar",
          "size": 261,
          "sha512": "19929bfb3839fc16ac27ccb1dcd37313d2f7eaeb8a6e2e5c659a3d1f16fdb4e4459f3d7fe9386f9e1efc865c7606ee655fec5b4a8a41a0a05220f417ce6d1fe8",
          "sha256": "f8eada52c1e95224998e867465d24c7a0dbcf1402ff5a8d0182e806025f828a4",
          "sha1": "529d6fdc9efbb027a0cae095875bb5e160c78aa9",
          "md5": "75e5b6ae36818d9a46076f50ba105f20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-bom",
          "version": {
            "requires": "1.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-kotlin"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-logback"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-retrofit2"
        },
        {
          "group": "com.linecorp.armeria",
          "module": "armeria-rxjava3"
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.uchuhimo",
          "module": "konf",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_hotspot",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_httpserver",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ag_server-0.0.3.jar",
          "url": "ag_server-0.0.3.jar",
          "size": 261,
          "sha512": "19929bfb3839fc16ac27ccb1dcd37313d2f7eaeb8a6e2e5c659a3d1f16fdb4e4459f3d7fe9386f9e1efc865c7606ee655fec5b4a8a41a0a05220f417ce6d1fe8",
          "sha256": "f8eada52c1e95224998e867465d24c7a0dbcf1402ff5a8d0182e806025f828a4",
          "sha1": "529d6fdc9efbb027a0cae095875bb5e160c78aa9",
          "md5": "75e5b6ae36818d9a46076f50ba105f20"
        }
      ]
    }
  ]
}
